### ISSUE TITLE
Cyclist Model Issues

### ISSUE THREAD

**Issue by bneukom** [d-wasserman/Complete_Street_Rule#18]
Hi!

The cyclist assets from https://github.com/d-wasserman/Complete_Street_Rule/tree/master/assets/Complete_Streets/LowPolygon3D.com_Cyclists have issues when exporting for example to Blender via FBX or Unreal via Datasmith. 

See:

![image](https://user-images.githubusercontent.com/16170133/85974304-70364980-b9d5-11ea-93e3-30fdc646fb2e.png)

The issue is that the inside and the outside of the models are separate geometry. This will lead to artifacts for example in Unreal as Opaque geometry is rendered two sided (what you see on the screenshot is actually the backside of the inside of the model).

This could be fixed by removing the "internal" faces and readjusting the normals in Blender.

**Comment by d-wasserman** [comment]
Hi @bneukom , 

The bicycle models have been THE most problematic models in the entire rule. Everything from the bicycle having separate color maps to this issue have plagued me too. 

Thank you for narrowing this down. I am not a pro at Blender, but I would gladly use another model if we can find one. Is this is a quick series of edits in blender?

**Comment by d-wasserman** [comment]
I am going to close this issue for now. It is a low priority item in that many may not use the cyclists native to the rule in other platforms. If you have a better low poly model, I am all ears.
