### ISSUE TITLE
Highway guardrail

### ISSUE THREAD

**Issue by xiaojianlin1989** [d-wasserman/Complete_Street_Rule#27]
I hope the author can add guardrails on both sides of the road to the rules

**Comment by d-wasserman** [comment]
I thought there was basic support for sides, but not specific guard rails. Do you have a model template of interest?

**Comment by d-wasserman** [comment]
For posterity, if anyone wants new highway guard rail files, please provide them, but you can get very close with a narrow sidewalk and Bridge_Display = "On, Regardless".
![image](https://user-images.githubusercontent.com/8280073/125219414-8aa63280-e279-11eb-940c-64692d205da5.png)
Closing for now.
