### ISSUE TITLE
Freeways can't be populated

### ISSUE THREAD

**Issue by Richcng** [d-wasserman/Complete_Street_Rule#28]
![image](https://user-images.githubusercontent.com/79707058/115725098-d5eb2c00-a381-11eb-994a-67028c6acd6d.png)
Both Freeway and FreewayEntry start rules don't allow any population with vehicles

**Comment by d-wasserman** [comment]
This feels fixable, but involves working a a UV space I am only so comfortable with. Let me see if it is just a lack of calling of the appropriate vehicle allocation rules. I am concerned about entry's less on the freeways.

**Comment by d-wasserman** [comment]
There is actually a lot I forgot about freeways and why they were difficult to work with. A recent commit at least makes some visual improvements to freeways, but this might need review from someone at Esri. 
![image](https://user-images.githubusercontent.com/8280073/132957658-b9f767d6-f3eb-441e-a025-220990fc0c31.png)
@Richcng

**Comment by d-wasserman** [comment]
Fundamentally I have found that supporting ever street shape perfectly would take almost a 5 -15% increase in code in the rule per start shape. As a result, I can only really provide basic support for each one beyond streets.

**Comment by d-wasserman** [comment]
@Richcng - still no resolution on this to date. I am going to close the issue for now, but will revisit in the future.
