### ISSUE TITLE
Roundabout mapping issues

### ISSUE THREAD

**Issue by Richcng** [d-wasserman/Complete_Street_Rule#29]
![image](https://user-images.githubusercontent.com/79707058/115725411-1c408b00-a382-11eb-89d8-9e8dcb7537dc.png)
![image](https://user-images.githubusercontent.com/79707058/115725464-2793b680-a382-11eb-90ed-b05d3e70dbd3.png)
Roundabouts UV mapping doesn't look right both in CE and UE

**Comment by d-wasserman** [comment]
I need to investigate this. Generally UV's with roundabouts have been problematic for a while.

**Comment by Richcng** [comment]
Hi David, 
Looks like Benjamin N. was able to fix this in the code:
_Apparently it is just a minor change to use world.xz uv instead of scope. This makes them align between neighboring shapes (because it uses world coordinates)_
Please contact him for more details.

**Comment by d-wasserman** [comment]
Awesome. Can sample code be shared or a pull request created for the CS Rule in the repo?

**Comment by d-wasserman** [comment]
We are discussing this PR. This is an interesting suggestion, but I have concerns given some of the results I am getting. I am using CE 2020. I am curious if it is a version issue too.

**Comment by d-wasserman** [comment]
I have been staring at this in CityEngine for like an hour, and if anyone has other code to try - happy to use it.
