### ISSUE TITLE
Missing Median_Tree_2_Height input

### ISSUE THREAD

**Issue by Richcng** [d-wasserman/Complete_Street_Rule#30]
In the “Median Plantings” section, there is no Median_Tree_2_Height input (see attached screenshot)
![median tree 2 missing](https://user-images.githubusercontent.com/79707058/115726307-e8199a00-a382-11eb-84f0-5baf10ac865f.jpg)

**Comment by d-wasserman** [comment]
I will make a note to try to add this in. I think there is very little reason not to include this option.

**Comment by d-wasserman** [comment]
That was a quick fix. Working on others.
