### ISSUE TITLE
Incorrect traffic lights position by left-hand traffic direction

### ISSUE THREAD

**Issue by Richcng** [d-wasserman/Complete_Street_Rule#31]
![Traffic Lights Issue_left hand_direction](https://user-images.githubusercontent.com/79707058/123640211-3afb4c00-d821-11eb-8e3a-da1892c20a36.jpg)
Changing attribute "Traffic Direction" has no impact on traffic light's position.
This might be a problem for projects located in left-hand traffic countries.

**Comment by d-wasserman** [comment]
I can investigate a fix for that. Generally traffic light positions are not ideal with the rule, but I can investigate switching them. Would gladly take a Pull Request for the change.

**Comment by d-wasserman** [comment]
@Richcng , this was addressed by a recent commit. Closing this issue. You can reopen.

**Comment by d-wasserman** [comment]
Spoke too soon. The signals are not facing the approaching direction. This is still better, and any real fix might require a new asset. For that reason, I am calling this "close enough" for now. New asset if contributed will be integrated.
