### ISSUE TITLE
Mirrored BUS sign on bus stops

### ISSUE THREAD

**Issue by Richcng** [d-wasserman/Complete_Street_Rule#34]
_On-Street Parking_ section, _Right/Left_Parking_Type: Parallel with Curbside Bus Stop_ 
The BUS writing on the street is mirrored. Is there a particular reason for that? 
In case it's not intentional, I guess it should be easy to fix.

![Complete Streets Rule_BUS sign_to be fixed_2_Screenshot 2021-09-21 143623](https://user-images.githubusercontent.com/79707058/134478412-5fed3dd3-3630-41d8-a3b1-53a99d199063.jpg)

![Complete Streets Rule_BUS sign_to be fixed_Screenshot 2021-09-21 143623](https://user-images.githubusercontent.com/79707058/134477640-74fe1760-9360-4a48-ae70-612b908ecd3e.jpg)

**Comment by d-wasserman** [comment]
That makes perfect sense. Ugh. I know what is causing it. Thanks. I can get to this.

**Comment by d-wasserman** [comment]
@Richcng - Please let me know if this resolves it.
