### ISSUE TITLE
Yellow Centerline is Missing for Crossings

### ISSUE THREAD

**Issue by hzxie** [d-wasserman/Complete_Street_Rule#39]
As shown in the figure below, the yellow centerline is not created for the selected crossing.

![image](https://user-images.githubusercontent.com/1730504/142557397-d7860056-6f9f-414e-b630-293a4a2dbedb.png)

**Comment by d-wasserman** [comment]
This is a known limitation of the Complete Street Rule as documented in its [user guide](https://github.com/d-wasserman/Complete_Street_Rule/wiki/Complete-Street-Rule-Wiki). I am going to close this issue unless you have a PR that can work for all center section shapes reasonably well. 
Methods to get around it: 

- The rule can adapt to slight angles that don't generate intersection shapes/crossings. 
- Manual model construction.
