### ISSUE TITLE
Stop markings will be covered by crosswalk markings while two road angle is too small

### ISSUE THREAD

**Issue by notbbshowmecode** [d-wasserman/Complete_Street_Rule#4]
hello~
      I  find a question while using this rule,stop markings will be Covered by crosswalk markings while two road angle is too small. Can you help me ?
                         thanks

**Comment by notbbshowmecode** [comment]
That is what i need !. if it can set "Begin_Crosswalk_To_Stop_Bar" for every lane ,that will more real.I try to rewrite cga for this .In addition，i try to add a  "Turn left to the transfer area" in the  crossing and it is too hard for me to connect two different shape in the cga. Can you give me some idea?What ever,you had give me  a lot of help,Thanks ,David
Jimz

**Comment by d-wasserman** [comment]
Great! Glad that helped. 
I have had trouble doing similar things in CGA. Are you trying to do a median with turn lane however? There is a setting for that. 
This might be a different question altogether though, so I have closed the issue for now. 
Thanks!
