### ISSUE TITLE
Street Lamps Overlap with the Bridges Above

### ISSUE THREAD

**Issue by hzxie** [d-wasserman/Complete_Street_Rule#40]
Similar to bridge piers, the lamps also overlap with the bridges above.

![image](https://user-images.githubusercontent.com/1730504/143197058-88a708b6-552b-4f2b-a9c0-792f5d8696ab.png)

I tried to add an empty bounding box by `extrude(y, 6.5)` to test whether the lamps overlap with the bridges above.

```
Sidewalk_Lamp(offset) -->
	alignScopeToGeometry(yUp,largest,0)
	alignScopeToAxes(y)
	center(xz)
	r(0,90,0)
	s(0,0,0)
	report("Objects.Street Lamp Count", 1)
	extrude(y, 6.5)
	Lamp_Check(offset)

Lamp_Check(offset) -->
    case overlaps(inter):
        NIL
    else:
        Lamp_Asset(offset)
    
Lamp_Asset(offset) -->
	t( SLight_Translate_X ,0, SLight_Translate_Z )
	r(0,90,0)
	t(offset,0,0)
	set(material.name,"Street_Lamp")
	label("Street Lamp")
	color( _ThematicRouter ("Pedestrian","lamp"))
	i(Street_Lamp_Object)
	Delete_Texture
```

However, it **sometimes** changes the orientation of the lamps, *i.e.* some lamps are not in the correct orientation, as shown in the figure below

![image](https://user-images.githubusercontent.com/1730504/143197818-f4f69bbb-0b2d-454a-a381-9a64baf04bf2.png)

How to solve the problem?

**Comment by d-wasserman** [comment]
That is very odd, but I would need to see sample files and a project folder. I don't see anything that might change the scope of the inserted object in your code if all you added was the lamp check. Maybe it is the r(0,90,0) in the second rule call? 

If you uncomment out the "@Hidden" Handle Parameters, I would just turn the lamps off manually using Handles. 

Code modifications to the Complete Street Rule are outside the scope of the repository. I would be interested in your final CGA code post modifications for review if you are willing to share that. However, I am closing this issue for now.

**Comment by hzxie** [comment]
Please try this file.
[Bridge-Test.zip](https://github.com/d-wasserman/Complete_Street_Rule/files/7616292/Bridge-Test.zip)
