### ISSUE TITLE
Pedestrian Paths & Curbs

### ISSUE THREAD

**Issue by Richcng** [d-wasserman/Complete_Street_Rule#44]
Hi David, 

A possible enhancement to put on the wish list: 

When using CE streets to create **pedestrian paths**, the usual trick is lowering down the street width to 0.
This way we end up with just two contiguous sidewalk segments.
However, when we try to do this applying the CSR, we can't get an homogeneous result because of the concrete curbs that are always set at the sidewalk limit (see screenshots).
Would it be possible to add an attribute to get rid of the curbs when not needed?
In my opinion, best would be an option to decide if we want to have right, left or both curbs for each sidewalk.

![Pedestrian trick_01](https://user-images.githubusercontent.com/79707058/191995774-3230c06c-560f-4f58-9eb7-6bb93759c1bb.jpg)

![Pedestrian trick_02](https://user-images.githubusercontent.com/79707058/191995807-beb47bc6-b105-45fc-99d8-bb6261640005.jpg)

**Comment by d-wasserman** [comment]
I am highly resistant to edits that add attributes...I think paths need a dedicated rule personally.

Until that happens, I could remove curbs when the ROW (street width) is set to zero. It would accomplish the same thing right?

**Comment by Richcng** [comment]
That's true, paths often require quite specific design. But it would be great if we could achieve a simple result without adding another rule to the project. 
Removing it for zero ROW values sounds like an effective alternative to get rid of the curbs. It would be great to have that possibility.

**Comment by d-wasserman** [comment]
![image](https://user-images.githubusercontent.com/8280073/193429150-79bd22f5-0ceb-42f2-9d00-a1136f87fb52.png)
I got something that works with the small issue I mentioned. This does work though. I will merge into main if you think it works.

**Comment by d-wasserman** [comment]
I did some more testing. There is some oddity with the shape. I did test, but let me know if you have any issues.

**Comment by Richcng** [comment]
Sorry for the delay, 
It worked as expected. 
Some screenshots: 
![CSR_2022 05 07](https://user-images.githubusercontent.com/79707058/198064228-b4ce410d-3b66-4e89-9495-f71c907b7673.jpg)
![CSR_2022 10 01_NoCurbs](https://user-images.githubusercontent.com/79707058/198064286-238f1980-e64e-4704-9b08-1e6b4e7ddaf3.jpg)
Thank you for implementing this so quickly!
