### ISSUE TITLE
Texture Problem

### ISSUE THREAD

**Issue by hsinclai** [d-wasserman/Complete_Street_Rule#9]
I read the instructions on the ESRI vegetation library but I am unsure how to connect the two data bases.....3d plant library/lumenrt in my assets folder but still not good. How do I tell complete streets to go find the trees for my sidwalks?

**Comment by d-wasserman** [comment]
By default, the complete street rule uses the Esri.lib library for trees. Can you provide more information on what you want to do? 

In short, you would need to replace the trees in Esri.lib with the corresponding trees of the same name or by changing how trees are referenced in the rule itself. I could use more information though.

**Comment by d-wasserman** [comment]
If you can give me more information about your problem I will try to help then. For now I'm going to leave a little more information. 
The complete street rule by default only connects to assets provided by Esri.lib Vegetation library. To use other assets you will need to rework the object insertion code that is provided by that library to connect to your assets.
